-- MySQL Script generated by MySQL Workbench
-- Sat Aug  1 20:41:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` ENUM('MUSICO','CONTRATANTE','ADMIN') NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `foto_perfil_url` VARCHAR(255) NULL,
  `status` ENUM('ATIVO','INATIVO','BLOQUEADO') NOT NULL DEFAULT ATIVO,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `uq_usuarios_email` (`email` ASC) VISIBLE,
  INDEX `idx_usuarios_tipo` (`tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `pais` VARCHAR(80) NOT NULL DEFAULT Brasil,
  PRIMARY KEY (`id_cidade`),
  INDEX `idx_cidades_nome_estado` (`nome` ASC, `estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`generos_musicais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`generos_musicais` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `uq_generos_nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`musicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musicos` (
  `id_musico` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nome_artistico` VARCHAR(120) NOT NULL,
  `biografia` TEXT NULL,
  `estilo_experiencia` TEXT NULL,
  `preco_hora` DECIMAL(10,2) NOT NULL,
  `id_cidade` INT NULL,
  `raio_atendimento_km` INT NULL,
  `instagram_url` VARCHAR(255) NULL,
  `whatsapp` VARCHAR(20) NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_musico`),
  UNIQUE INDEX `uq_musicos_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_musicos_cidade` (`id_cidade` ASC) VISIBLE,
  INDEX `idx_musicos_nome_artistico` (`nome_artistico` ASC) VISIBLE,
  CONSTRAINT `fk_musicos_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_musicos_cidades`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`cidades` (`id_cidade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`contratantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contratantes` (
  `id_contratante` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_cidade` INT NULL,
  `endereco_padrao` VARCHAR(180) NULL,
  `numero_padrao` VARCHAR(20) NULL,
  `complemento_padrao` VARCHAR(80) NULL,
  `quantidade_contratacoes` INT NOT NULL DEFAULT 0,
  `nota_media` DECIMAL(3,2) NULL,
  PRIMARY KEY (`id_contratante`),
  UNIQUE INDEX `uq_contratantes_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_contratantes_cidade` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_contratantes_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contratantes_cidades`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`cidades` (`id_cidade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`musico_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musico_generos` (
  `id_musico` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_musico`),
  CONSTRAINT `fk_musico_generos_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_musico_generos_generos`
    FOREIGN KEY (`id_genero`)
    REFERENCES `mydb`.`generos_musicais` (`id_genero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`formas_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formas_pagamento` (
  `id_forma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_forma_pagamento`),
  UNIQUE INDEX `uq_formas_pagamento_nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`musico_formas_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musico_formas_pagamento` (
  `id_musico` INT NOT NULL,
  `id_forma_pagamento` INT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_musico`),
  CONSTRAINT `fk_mfp_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mfp_formas`
    FOREIGN KEY (`id_forma_pagamento`)
    REFERENCES `mydb`.`formas_pagamento` (`id_forma_pagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`disponibilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disponibilidades` (
  `id_disponibilidade` INT NOT NULL AUTO_INCREMENT,
  `id_musico` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `status` ENUM('DISPONIVEL','INDISPONIVEL','RESERVADO') NOT NULL DEFAULT DISPONIVEL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_disponibilidade`),
  INDEX `idx_disponibilidades_musico_periodo` (`id_musico` ASC, `data_inicio` ASC, `data_fim` ASC) VISIBLE,
  CONSTRAINT `fk_disponibilidades_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`solicitacoes_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitacoes_show` (
  `id_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `id_musico` INT NOT NULL,
  `id_contratante` INT NOT NULL,
  `id_cidade` INT NULL,
  `endereco_evento` VARCHAR(180) NOT NULL,
  `numero_evento` VARCHAR(20) NULL,
  `complemento_evento` VARCHAR(80) NULL,
  `telefone_evento` VARCHAR(20) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `duracao_horas` DECIMAL(4,2) NOT NULL,
  `tipo_evento` ENUM('PUBLICO','PRIVADO') NOT NULL,
  `dress_code` VARCHAR(100) NULL,
  `informacoes_adicionais` TEXT NULL,
  `valor_proposto` DECIMAL(10,2) NULL,
  `valor_calculado` DECIMAL(10,2) NULL,
  `status` ENUM('PENDENTE','ACEITA','RECUSADA','CANCELADA') NOT NULL DEFAULT PENDENTE,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `respondido_em` DATETIME NULL,
  PRIMARY KEY (`id_solicitacao`),
  INDEX `idx_solicitacoes_musico_status` (`id_musico` ASC, `status` ASC) VISIBLE,
  INDEX `idx_solicitacoes_contratante` (`id_contratante` ASC) VISIBLE,
  INDEX `idx_solicitacoes_data` (`data_inicio` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacoes_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitacoes_contratantes`
    FOREIGN KEY (`id_contratante`)
    REFERENCES `mydb`.`contratantes` (`id_contratante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitacoes_cidades`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`cidades` (`id_cidade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shows` (
  `id_show` INT NOT NULL AUTO_INCREMENT,
  `id_solicitacao` INT NOT NULL,
  `id_musico` INT NOT NULL,
  `id_contratante` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `status` ENUM('CONFIRMADO','REALIZADO','CANCELADO') NOT NULL DEFAULT CONFIRMADO,
  `forma_pagamento_combinada` VARCHAR(160) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_show`),
  UNIQUE INDEX `uq_shows_solicitacao` (`id_solicitacao` ASC) VISIBLE,
  INDEX `idx_shows_musico_data` (`id_musico` ASC, `data_inicio` ASC) VISIBLE,
  INDEX `idx_shows_contratante` (`id_contratante` ASC) VISIBLE,
  CONSTRAINT `fk_shows_solicitacoes`
    FOREIGN KEY (`id_solicitacao`)
    REFERENCES `mydb`.`solicitacoes_show` (`id_solicitacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shows_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shows_contratantes`
    FOREIGN KEY (`id_contratante`)
    REFERENCES `mydb`.`contratantes` (`id_contratante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_show` INT NOT NULL,
  `id_forma_pagamento` INT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDENTE','PAGO','CANCELADO','REEMBOLSADO') NOT NULL DEFAULT PENDENTE,
  `data_pagamento` DATETIME NULL,
  `referencia_externa` VARCHAR(120) NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `idx_pagamentos_show` (`id_show` ASC) VISIBLE,
  CONSTRAINT `fk_pagamentos_shows`
    FOREIGN KEY (`id_show`)
    REFERENCES `mydb`.`shows` (`id_show`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pagamentos_formas`
    FOREIGN KEY (`id_forma_pagamento`)
    REFERENCES `mydb`.`formas_pagamento` (`id_forma_pagamento`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fotos_musico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fotos_musico` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `id_musico` INT NOT NULL,
  `url_foto` VARCHAR(255) NOT NULL,
  `legenda` VARCHAR(160) NULL,
  `ordem_exibicao` INT NOT NULL DEFAULT 0,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_foto`),
  INDEX `idx_fotos_musico` (`id_musico` ASC, `ordem_exibicao` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`anexos_solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anexos_solicitacao` (
  `id_anexo` INT NOT NULL AUTO_INCREMENT,
  `id_solicitacao` INT NOT NULL,
  `url_arquivo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(160) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_anexo`),
  INDEX `idx_anexos_solicitacao` (`id_solicitacao` ASC) VISIBLE,
  CONSTRAINT `fk_anexos_solicitacoes`
    FOREIGN KEY (`id_solicitacao`)
    REFERENCES `mydb`.`solicitacoes_show` (`id_solicitacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `id_show` INT NOT NULL,
  `id_avaliador_usuario` INT NOT NULL,
  `id_avaliado_usuario` INT NOT NULL,
  `nota` TINYINT NOT NULL,
  `comentario` TEXT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `idx_avaliacoes_show` (`id_show` ASC) VISIBLE,
  INDEX `idx_avaliacoes_avaliado` (`id_avaliado_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacoes_shows`
    FOREIGN KEY (`id_show`)
    REFERENCES `mydb`.`shows` (`id_show`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacoes_avaliador`
    FOREIGN KEY (`id_avaliador_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacoes_avaliado`
    FOREIGN KEY (`id_avaliado_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`perguntas_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perguntas_perfil` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `id_musico` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `pergunta` TEXT NOT NULL,
  `resposta` TEXT NULL,
  `respondida_em` DATETIME NULL,
  `status` ENUM('PUBLICADA','OCULTA') NOT NULL DEFAULT PUBLICADA,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pergunta`),
  INDEX `idx_perguntas_musico` (`id_musico` ASC, `status` ASC) VISIBLE,
  CONSTRAINT `fk_perguntas_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_perguntas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`visualizacoes_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visualizacoes_perfil` (
  `id_visualizacao` INT NOT NULL AUTO_INCREMENT,
  `id_musico` INT NOT NULL,
  `id_usuario` INT NULL,
  `ip_origem` VARCHAR(45) NULL,
  `visualizado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_visualizacao`),
  INDEX `idx_visualizacoes_musico_data` (`id_musico` ASC, `visualizado_em` ASC) VISIBLE,
  CONSTRAINT `fk_visualizacoes_musicos`
    FOREIGN KEY (`id_musico`)
    REFERENCES `mydb`.`musicos` (`id_musico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_visualizacoes_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
